---
apiVersion: v1
kind: Namespace
metadata:
  name: mygatekeeper
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: gatekeeper-operator
  namespace: mygatekeeper
spec:
  displayName: Gatekeeper Operator Upstream
  image: 'quay.io/gatekeeper/gatekeeper-operator-bundle-index:latest'
  publisher: github.com/gatekeeper/gatekeeper-operator
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gatekeeper-operator
  namespace: mygatekeeper
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator-sub
  namespace: mygatekeeper
spec:
  name: gatekeeper-operator
  channel: stable
  source: gatekeeper-operator
  sourceNamespace: mygatekeeper
